### ISSUE TITLE
Data from file is not escaped for json

### ISSUE THREAD

**Issue by aqos156** [TsakiDev/gitea-comment#2]
As the title says, data from the file are not formatted for json. Any double quotes or backslashes will break the json formatting. I have to do this with sed manually for each logfile.

```
sed 's/\\\\/\\\\\\\\/g' file.log | sed 's/"/\\\\"/g' > file-out.log
```

The formatting of sed backslashes is weird because of drone.yml also escapes backslashes.

Complete working escaping step:

```
- name: Escape json
  image: alpine
  commands:
    - sed 's/\\\\/\\\\\\\\/g' output.log | sed 's/"/\\\\"/g' > output-out.log
```

I would suggest to use a kind of json escaping library, I do not know if my solution of replacing just `\` with `\\` and `"` with `\"` has any edge cases.
